name: Terraform Plan
on:
  pull_request:
    types: [closed]
    branches:
      - desarrollo

permissions:
  pull-requests: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
    steps:
      - name: Chechout this repo
        uses: actions/checkout@v4

      - name: Using Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform init
        run: terraform init

      - name: Format
        run: terraform fmt 

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan 
