name: Terraform Plan
on:
  # pull_request:
  #   types: [closed]
  push:
    branches:
      - feature/pipe

permissions:
  pull-requests: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Chechout this repo
        uses: actions/checkout@v4

      - name: Using Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform init
        run: terraform init

      - name: Format
        run: terraform fmt

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan
