name: Terraform Plan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Mensaje1
      run: Estas haciendo un PR desde Feature hasta Main!


         
  
