name: Terraform Apply
on:
  pull_request:
    types: [closed]  
    branches:
      - 'main'
  
permissions:
  pull-requests: write

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Chechout this repo
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1

      - name: Using Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: terraform init

      - name: Format
        run: terraform fmt

      - name: Validate
        run: terraform validate

      - name: Show
        run: terraform show

      - name: Apply
        run: terraform apply -auto-approve || echo "Error detected"

      - name: Destroy on error
        if: ${{ failure() }}
        run: terraform destroy -auto-approve

      - name: List
        run: |
          ls
          archivos=$(ls)
          if echo "$archivos" | grep -q 'terraform.tfstate'; then
            echo "si esta tf state"
            if aws s3 cp terraform.tfstate s3://newyorkmets-bucket3/; then
              echo "Se ha enviado a S3"
            else
              echo "Error al moverlo, ejecutando destroy"
              terraform destroy -auto-approve
            fi
          else
            echo "no esta tf state"
          fi

      - name: Sleep 10 mins
        run: sleep 600s

      - name: Destroy
        run: terraform destroy -auto-approve
