name: Terraform Apply
on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
  
permissions:
  pull-requests: write

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
    steps:
      - name: Chechout this repo
        uses: actions/checkout@v4

      - name: Using Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Format
        run: terraform fmt

      - name: Validate
        run: terraform validate

      - name: Show
        run: terraform show

      - name: Apply
        run: terraform apply -auto-approve
        
      - name: Sleep 20s
        run: sleep 20s

      - name: Destroy
        run: terraform destroy -auto-approve
