name: Terraform Apply
on:
  # pull_request:
  #   types: [closed]
  push:
    branches:
      #- 'main'
      - feature/pipe
  
permissions:
  pull-requests: write

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
    steps:
      - name: Chechout this repo
        uses: actions/checkout@v4

      - name: Using Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: terraform init

      - name: Format
        run: terraform fmt

      - name: plan
        run: terraform plan

      - name: Validate
        run: terraform validate

      - name: Apply
        run: terraform apply -auto-approve


      - name: Move state to s3
        run: |
          echo "Lista archivos"
          ls
          echo "validacion de s3"
          aws s3 ls
          if aws s3 cp terraform.tfstate s3://newyorkmets-bucket3/; then
            echo "¡Archivo movido a S3 exitosamente!"
          else
            echo "¡Error al mover archivo a S3!"
          fi


        
      - name: Sleep 5 mins
        run: sleep 3s

      - name: Destroy
        run: terraform destroy -auto-approve
